import "server-only";
import vaultData from "@/data/vault.json";

// The Jordan Vault is a file-backed, browse-only catalog (separate from the
// 378-card MJ Hierarchy and the Supabase `cards` table). Data is generated by
// jordan-vault/build-app-data.ts. Image paths point at static files in
// public/vault/; a missing file falls back to CardThumb's placeholder.
export type VaultCard = {
  id: number;
  slug: string | null;
  name: string | null;
  year: number | null;
  manufacturer: string | null;
  brand: string | null;
  cardNumber: string | null;
  cardType: string | null;
  tier: number | null;
  page: number | null;
  row: number | null;
  frontImage: string | null;
  backImage: string | null;
  psaPopReport: string | null;
};

/** Slim shape passed to the client grid (keeps the payload small). */
export type VaultTile = Pick<
  VaultCard,
  "id" | "name" | "year" | "manufacturer" | "cardNumber" | "cardType" | "tier" | "frontImage"
>;

export const VAULT = vaultData as VaultCard[];

export function getVaultCard(id: number): VaultCard | null {
  return VAULT.find((c) => c.id === id) ?? null;
}

export function vaultTiles(): VaultTile[] {
  return VAULT.map((c) => ({
    id: c.id,
    name: c.name,
    year: c.year,
    manufacturer: c.manufacturer,
    cardNumber: c.cardNumber,
    cardType: c.cardType,
    tier: c.tier,
    frontImage: c.frontImage,
  }));
}

export function relatedVaultCards(card: VaultCard, limit = 6): VaultCard[] {
  return VAULT.filter((c) => c.id !== card.id && c.manufacturer === card.manufacturer).slice(0, limit);
}
