#!/usr/bin/env python3
"""Pixelize the Taino coqui petroglyph into the brand logo mark.

Reads scripts/taino-coqui-source.jpg (a black silhouette), crops to the inked
bounding box, downsamples to a ~28px-wide monochrome grid, and emits:
  - lib/coqui-glyph-data.ts : the boolean grid the CoquiGlyph component renders
  - app/icon.svg, public/icon.svg : the favicon / app icon (green on dungeon blue)

Re-run after swapping the source to regenerate everything:
    python3 scripts/pixelize-glyph.py
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "scripts", "taino-coqui-source.jpg")

WIDTH = 28          # target grid width (height derived from aspect)
INK_BBOX = 128      # luminance below this counts as ink when finding the crop box
THRESHOLD = 90      # resized luminance above this becomes a filled pixel

# Brand colors (favicon is a static asset → fixed hex, not theme vars).
ACCENT = "#5fd35f"  # Coqui green
BG = "#0c1026"      # dungeon-blue background


def build_grid():
    im = Image.open(SRC).convert("L")
    mask = im.point(lambda p: 255 if p < INK_BBOX else 0)
    bbox = mask.getbbox()
    crop = mask.crop(bbox)
    cw, ch = crop.size
    h = max(1, round(WIDTH * ch / cw))
    small = crop.resize((WIDTH, h), Image.BILINEAR)
    px = small.load()
    rows = []
    for y in range(h):
        rows.append("".join("1" if px[x, y] > THRESHOLD else "0" for x in range(WIDTH)))
    return rows


def write_data(rows):
    w = len(rows[0])
    h = len(rows)
    body = ",\n  ".join(f'"{r}"' for r in rows)
    ts = (
        "// AUTO-GENERATED by scripts/pixelize-glyph.py — do not edit by hand.\n"
        "// Pixelized Taino coqui petroglyph; '1' = a filled pixel.\n"
        f"export const GLYPH_W = {w};\n"
        f"export const GLYPH_H = {h};\n"
        f"export const COQUI_GLYPH: string[] = [\n  {body},\n];\n"
    )
    with open(os.path.join(ROOT, "lib", "coqui-glyph-data.ts"), "w") as f:
        f.write(ts)
    return w, h


def write_icons(rows):
    w = len(rows[0])
    h = len(rows)
    # Fit the glyph into a 512 box with ~12% maskable-safe padding, centered.
    safe = 512 * 0.76
    cell = safe / max(w, h)
    ox = (512 - cell * w) / 2
    oy = (512 - cell * h) / 2
    rects = []
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            if c == "1":
                rx = round(ox + x * cell, 2)
                ry = round(oy + y * cell, 2)
                rects.append(
                    f'<rect x="{rx}" y="{ry}" width="{round(cell + 0.6, 2)}" '
                    f'height="{round(cell + 0.6, 2)}" fill="{ACCENT}"/>'
                )
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" '
        'viewBox="0 0 512 512" shape-rendering="crispEdges">\n'
        f'<rect width="512" height="512" rx="96" fill="{BG}"/>\n'
        + "".join(rects)
        + "\n</svg>\n"
    )
    for path in ("app/icon.svg", "public/icon.svg"):
        with open(os.path.join(ROOT, path), "w") as f:
            f.write(svg)
    return len(rects)


def main():
    rows = build_grid()
    print(f"grid: {len(rows[0])}x{len(rows)}")
    for r in rows:
        print(r.replace("1", "#").replace("0", "."))
    w, h = write_data(rows)
    n = write_icons(rows)
    print(f"\nwrote lib/coqui-glyph-data.ts ({w}x{h}) and app|public/icon.svg ({n} pixels)")


if __name__ == "__main__":
    main()
